# Generated by Django 5.0.1 on 2024-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_text', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='./static/img')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
