# Generated by Django 5.0.1 on 2024-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./img'),
        ),
    ]
