# Generated by Django 5.0.1 on 2024-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0003_complaint_complainttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
