# Generated by Django 5.0.1 on 2024-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0004_complaint_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('alertText', models.TextField()),
                ('alertby', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('atime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
